version: "3"
services:
  rocketchat:
    image: wissoft/rocketchat:1.3-amd64
    networks:
    - rocketchat-network
    environment:
    - PORT=8006
    - MONGO_DATABASE=${MONGO_DATABASE-rocketchat}
    - MONGO_HOST=${MONGO_HOST-mongo:27017}
    - MONGO_OPLOG_HOST=${MONGO_OPLOG_HOST-mongo:27017}
    - ROOT_URL=http://127.0.0.1:8006
    ports:
    - "8006:8006"
  mongo:
    image: mongo:3.2-jessie
    networks:
    - rocketchat-network
    volumes:
    - /srv/mongo:/data/db
    command: mongod --oplogSize 128 --replSet rs0
networks:
  rocketchat-network:
    driver: bridge
