version: "2"
services:
  hubot-rocketchat:
    image: wissoft/hubot-rocketchat:2.0-amd64
    networks:
    - rocketchat_rocketchat-network
    environment:
    - AUTH_ATTEMPTS=${AUTH_ATTEMPTS}
    - DEBUG=${DEBUG}
    - EXTERNAL_SCRIPTS=${EXTERNAL_SCRIPTS}
    - HUBOT_NAME=${HUBOT_NAME}
    - LISTEN_ON_ALL_PUBLIC=${LISTEN_ON_ALL_PUBLIC}
    - REQUIRED_PRIVATE_CHANNELS=${REQUIRED_PRIVATE_CHANNELS}
    - RESPOND_TO_DM=${RESPOND_TO_DM}
    - ROCKETCHAT_PASSWORD=${ROCKETCHAT_PASSWORD}
    - ROCKETCHAT_ROOM=${ROCKETCHAT_ROOM}
    - ROCKETCHAT_URL=${ROCKETCHAT_URL}
    - ROCKETCHAT_USER=${ROCKETCHAT_USER}
    - TZ=${TZ}
    # hubot-happy-birthder
    - BIRTHDAY_CHANNEL_BLACKLIST=${BIRTHDAY_CHANNEL_BLACKLIST}
    - BIRTHDAY_CHANNEL_MESSAGE=${BIRTHDAY_CHANNEL_MESSAGE}
    - BIRTHDAY_CHANNEL_TTL=${BIRTHDAY_CHANNEL_TTL}
    - BIRTHDAY_LOGGING_CHANNEL=${BIRTHDAY_LOGGING_CHANNEL}
    - COMPANY_NAME=${COMPANY_NAME}
    - CREATE_BIRTHDAY_CHANNELS=${CREATE_BIRTHDAY_CHANNELS}
    - ENABLE_PITCHING_IN_SURVEY=${ENABLE_PITCHING_IN_SURVEY}
    - HAPPY_REMINDER_SCHEDULER=${HAPPY_REMINDER_SCHEDULER}
    - NUMBER_OF_DAYS_IN_ADVANCE=${NUMBER_OF_DAYS_IN_ADVANCE}
    - TENOR_API_KEY=${TENOR_API_KEY}
    - TENOR_BLACKLIST=${TENOR_BLACKLIST}
    - TENOR_IMG_LIMIT=${TENOR_IMG_LIMIT}
    - TENOR_SEARCH_TERM=${TENOR_SEARCH_TERM}
    # hubot-huntflow-reloaded
    - BASE_SERVER_URL=${BASE_SERVER_URL}
    - CHANNEL_NAME=${CHANNEL_NAME}
    - REDIS_HOST=${REDIS_HOST}
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    - REDIS_PORT=${REDIS_PORT}
    - SERVER_USER_EMAIL=${SERVER_USER_EMAIL}
    - SERVER_USER_PASSWORD=${SERVER_USER_PASSWORD}
    # hubot-pugme
    - PUGS_LIMIT=${PUGS_LIMIT}
    # hubot-redis-brain
    - REDIS_URL=${REDIS_URL}
    # hubot-viva-las-vegas
    - GOOGLE_API=${GOOGLE_API}
    - GOOGLE_CALENDAR_NAME=${GOOGLE_CALENDAR_NAME}
    - GOOGLE_CLIENT_EMAIL=${GOOGLE_CLIENT_EMAIL}
    - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
    - LEAVE_COORDINATION_CHANNEL=${LEAVE_COORDINATION_CHANNEL}
    - MAXIMUM_LENGTH_OF_LEAVE=${MAXIMUM_LENGTH_OF_LEAVE}
    - MAXIMUM_LENGTH_OF_WAIT=${MAXIMUM_LENGTH_OF_WAIT}
    - MINIMUM_DAYS_BEFORE_REQUEST=${MINIMUM_DAYS_BEFORE_REQUEST}
    - VIVA_REMINDER_SCHEDULER=${VIVA_REMINDER_SCHEDULER}
    - VIVA_REPORT_SCHEDULER=${VIVA_REPORT_SCHEDULER}
    volumes:
    - ./packages:/root/hubot/packages
    - ./scripts:/root/hubot/scripts
    ports:
    - "9229:9229"
  redis:
    image: wissoft/redis:5.0-amd64
    networks:
    - rocketchat_rocketchat-network
    environment:
    # Enable AOF
    - REDIS_CONF_appendonly=yes
    # Disable RDB
    - REDIS_CONF_save=
    - REDIS_CONF_loglevel=notice
    - REDIS_CONF_bind=0.0.0.0
    volumes:
    - /srv/redis-dump:/dump
networks:
  rocketchat_rocketchat-network:
    external: true
